#!/bin/sh -eu
#
# Bootstrap full installation
#
# curl -sSL https://git.io/biiim | sh -s "tools;docker;crane;docker-machine"

# Set locales
sudo locale-gen en_US en_US.UTF-8
sudo dpkg-reconfigure locales

# Install dotfiles
curl -sSL https://raw.github.com/thbkrkr/dotfiles/master/bim | sh

export IFS=";"
for module in $1
do
    [ -f ~/.dotfiles/install/install-$module.sh ] \
        && ~/.dotfiles/install/install-$module.sh && echo " --> Module $module OK" \
        || echo " --> Module $module unknown"
done
