#!/bin/sh

# curl -sL https://raw.github.com/thbkrkr/dotfiles/master/bim | sh
# curl -sL http://goo.gl/jzfMdY | sh

sudo /usr/bin/apt-get install -y git

git clone https://github.com/thbkrkr/dotfiles.git ~/.dotfiles

~/.dotfiles/install
