#!/bin/sh

# @deps : apt-get, git

sudo apt-get install -y --force-yes \
    zsh \
    tmux \
    vim \
    iftop \
    htop \
    unzip \
    tree \
    dos2unix \
    curl \
    jq

# Install zsh
if [ $(which zsh > /dev/null; echo $?) -eq 0 ]; then
    zsh
    sudo chsh -s `which zsh` `whoami`
fi

cd ~/.dotfiles

if [ ! -d ~/.oh-my-zsh ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

cp -f pure-thb.zsh-theme ~/.oh-my-zsh/themes/

gitUserName=$(git config --global user.name)
gitUserEmail=$(git config --global user.email)

# Copy all dotfiles
find . -maxdepth 1 -type f -name ".*" -exec cp {} ~ \;

git config --global user.name $gitUserName
git config --global user.email $gitUserEmail


[ "x$gitUserName" = "x" ] && echo "Please update your git user.name, user.email : vi ~/.gitconfig"
